# Generated by Django 4.2.5 on 2023-10-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_first_name_user_last_name_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[(1, "normal"), (2, "company"), (3, "admin")], default=1
            ),
        ),
    ]
