# Generated by Django 4.2.5 on 2023-11-13 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_companyprofile_description_companyprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="image",
            field=models.FileField(
                blank=True,
                default="/default/company-avatar-default.png",
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
