# Generated by Django 4.2.5 on 2023-11-13 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_companyprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="payment_method_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "card"),
                        (2, "cash"),
                        (3, "online"),
                        (4, "check"),
                        (5, "credit"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="service_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "piano"),
                        (2, "furniture"),
                        (3, "workshop"),
                        (4, "garden"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
