# Generated by Django 4.2.7 on 2023-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_companyprofile_payment_method_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofileimage",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
        migrations.DeleteModel(
            name="CompanyProfileImage",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
