# Generated by Django 4.2.7 on 2023-12-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_companyprofileimage_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "normal"),
                    (2, "company"),
                    (3, "admin"),
                    (4, "support"),
                    (10, "superuser"),
                ],
                default=1,
            ),
        ),
    ]
