# Generated by Django 4.2.16 on 2024-11-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices_app", "0006_invoicemodel_final_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicemodel",
            name="state",
            field=models.IntegerField(
                choices=[(1, "pending"), (2, "payed")], default=1
            ),
        ),
    ]
