# Generated by Django 4.2.8 on 2023-12-26 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifier_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationmodel",
            name="content",
        ),
    ]
