# Generated by Django 4.2.5 on 2023-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderDestinationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.IntegerField(
                        choices=[
                            (1, "Apartment building"),
                            (2, "Row house"),
                            (3, "Detached house"),
                            (4, "Semi-detached house"),
                            (5, "Luhtitalo"),
                            (6, "Storage space"),
                            (7, "Company relocation"),
                            (8, "Other"),
                        ],
                        default=1,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("move_date", models.DateField()),
                ("persons_moving", models.IntegerField(default=0)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderOriginModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.IntegerField(
                        choices=[
                            (1, "Apartment building"),
                            (2, "Row house"),
                            (3, "Detached house"),
                            (4, "Semi-detached house"),
                            (5, "Luhtitalo"),
                            (6, "Storage space"),
                            (7, "Company relocation"),
                            (8, "Other"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "moving_choice",
                    models.IntegerField(
                        choices=[
                            (1, "all the items"),
                            (2, "only a part of the items"),
                            (3, "only a piano move"),
                        ],
                        default=1,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(default=False)),
                ("apartment_size", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
