# Generated by Django 4.2.5 on 2023-10-22 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0002_ordermodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
