# Generated by Django 4.2.5 on 2023-11-08 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0004_rename_name_ordermodel_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="persons_moving",
            new_name="living_people",
        ),
        migrations.AddField(
            model_name="orderdestinationmodel",
            name="order",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders_app.ordermodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderoriginmodel",
            name="order",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders_app.ordermodel",
            ),
            preserve_default=False,
        ),
    ]
