# Generated by Django 4.2.5 on 2023-11-08 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0005_rename_persons_moving_ordermodel_living_people_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="move_date",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="move_dates",
            field=models.ManyToManyField(to="orders_app.movedate"),
        ),
    ]
