# Generated by Django 4.2.5 on 2023-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0007_orderpicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "in_process"),
                    (3, "done"),
                    (4, "canceled"),
                ],
                default=1,
            ),
        ),
    ]
