# Generated by Django 4.2.7 on 2023-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0009_alter_orderdestinationmodel_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
