# Generated by Django 4.2.14 on 2024-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0011_orderdestinationmodel_geometry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdestinationmodel",
            old_name="geometry",
            new_name="location_point",
        ),
        migrations.RenameField(
            model_name="orderoriginmodel",
            old_name="geometry",
            new_name="location_point",
        ),
    ]
