# Generated by Django 4.2.14 on 2024-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders_app",
            "0012_rename_geometry_orderdestinationmodel_location_point_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="google_map_distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
