# Generated by Django 4.2.15 on 2024-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0013_ordermodel_google_map_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="price",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=1000),
        ),
    ]
