# Generated by Django 4.2.7 on 2023-12-11 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticketmessagemodel",
            old_name="modified_at",
            new_name="updated_date",
        ),
    ]
