# Generated by Django 4.2.7 on 2023-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets_app", "0002_rename_modified_at_ticketmessagemodel_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketmodel",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "normal"), (2, "urgent")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "new ticket"),
                    (2, "pending for user answer"),
                    (3, "pending for support answer"),
                    (4, "fixed"),
                    (5, "closed"),
                ],
                default=1,
            ),
        ),
    ]
