# Generated by Django 4.2.7 on 2023-12-29 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("profiles_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprofile",
            old_name="founded_date",
            new_name="established_date",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="traffic_permit_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
