# Generated by Django 4.2.7 on 2024-01-01 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles_app", "0003_alter_companyprofile_payment_method_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="rate",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
