# Generated by Django 4.2.7 on 2024-01-02 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles_app", "0005_adminprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="image",
            field=models.FileField(
                blank=True,
                default="/default/company-avatar-default.png",
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.FileField(
                blank=True,
                default="/default/company-avatar-default.png",
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
