# Generated by Django 4.2.7 on 2024-01-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles_app", "0006_adminprofile_image_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "verified"),
                    (3, "rejected"),
                    (4, "suspended"),
                ],
                default=1,
            ),
        ),
    ]
