# Generated by Django 4.2.14 on 2024-07-21 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0007_companyprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
