# Generated by Django 4.2.15 on 2024-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0008_companyprofile_location_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
