# Generated by Django 4.2.5 on 2023-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0002_alter_offermodel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="offertemplate",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
