# Generated by Django 4.2.7 on 2023-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0005_offermessagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermessagemodel",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
