# Generated by Django 4.2.7 on 2023-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0007_alter_offermessagemodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offermessagemodel",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
