# Generated by Django 4.2.7 on 2024-01-02 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0008_offermessagemodel_is_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreedoffer",
            options={"ordering": ["-created_date"]},
        ),
    ]
