# Generated by Django 4.2.15 on 2024-08-24 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers_app", "0009_alter_agreedoffer_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OfferTemplate",
            new_name="OfferTemplateModel",
        ),
    ]
